import sys
import trace

# create a Trace object, telling it what to ignore, and whether to
# do tracing or line-counting or both.


tracer = trace.Trace(ignoredirs=[sys.prefix, sys.exec_prefix], trace=0, count=1)


s = """
import nose
nose.run('zuper_typing_tests')
nose.run('zuper_ipce_tests')
#from zuper_ipce_tests.test_z_from_testobjs_autogenerated import all_cases

#all_cases()
"""

# run the new command using the given tracer
tracer.run(s)

# make a report, placing output in /tmp
r = tracer.results()
r.write_results(show_missing=True, coverdir="trace-cover")
